config/routes.rb
Fvs::Application.routes.draw do
  root 'posts#index'

  match '/flagged',     to: 'posts#flagged',     via: 'get'
  match '/members',     to: 'users#index',       via: 'get'
  match '/search',      to: 'search#search',     via: 'get'

  devise_for :users

  resources :users, only: [:show] do
    resources :posts, except: [:index], path: 'listings' do
      patch 'flag', on: :member
      patch 'unflag', on: :member
    end
  end
end

app/models/post.rb
require 'elasticsearch/model'

class Post < ActiveRecord::Base
  extend FriendlyId
    friendly_id :slugged_candidates, use: :slugged

  def slugged_candidates
    [
      :title,
      :title_and_author,
      [:title_and_author, :id]
    ]
  end

  def title_and_author
    "#{title} #{author.name}"
  end
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name BONSAI_INDEX_NAME

  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 25 }
  validates :content, presence: true, length: { maximum: 250 }
  validates_presence_of :author
end

app/models/user.rb
require 'elasticsearch/model'

class User < ActiveRecord::Base
  extend FriendlyId
    friendly_id :slugged_candidates, use: :slugged

  def slugged_candidates
    [
      :name,
      [:name, :id]
    ]
  end

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name BONSAI_INDEX_NAME

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, foreign_key: :author_id
  validates :name, :slug, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Check if the current slug is not the cannonical one.
  def bad_slug?(object)
    params[:id] != object.to_param
  end

  def redirect_to_good_slug(object)
    redirect_to params.merge({
      :controller => controller_name,
      :action => params[:action],
      :id => object.to_param,
      :status => :moved_permanently
    })
  end

  protected

  def after_sign_in_path_for(resource_name)
    root_path
  end

  def after_sign_in_path_for(resource)
   root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  private

  def permission_denied
    head 403
  end

  def user_not_authorized
    self.response_body = nil
    flash[:error] = "You are not authorized to perform this action."
    redirect_to root_path and return
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :flag, :unflag, :edit, :update, :destroy]
  after_action :verify_authorized, except: [:index, :show, :equipment]

  def index
    @users = User.last(10).reverse
    @posts = Post.last(10).reverse
  end

  def equipment
    @posts = Post.search('equipment')
      .records.where(flagged: false)
      .paginate(page: params[:page])

    render action: 'index'
  end

  def show
  end

  def flagged
    @posts = Post.where(flagged: true).paginate(page: params[:page]).order('created_at DESC')
    authorize @posts
  end

  def flag
    authorize @post
    @flagged_posts_count = Post.where(flagged: true).count
    if !@post.flagged
      if @post.update_attribute(:flagged, true)
        respond_to do |format|
          format.html { redirect_to listings_path }
          format.json { head :no_content }
          format.js   { render layout: false }
        end
      end
    else
      flash[:error] = "This listing has already been flagged"
    end
  end

  def unflag
    authorize @post
    @flagged_posts_count = Post.where(flagged: true).count
    if @post.flagged
      if @post.update_attribute(:flagged, false)
        respond_to do |format|
          format.html { redirect_to listings_path }
          format.json { head :no_content }
          format.js   { render layout: false }
        end
      end
    else
      flash[:error] = "This listing has is not flagged"
    end
  end

  def new
    @user = User.find(params[:user_id])

    if @user.id != current_user.id
      flash[:error] = "You are not authorized to perform this action"
      redirect_to listings_path
    end

    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    authorize @post

    respond_to do |format|
      if @post.save!
        format.html { redirect_to listings_path }
        format.js
      else
        format.html { redirect_to :back, alert: 'Listing Failed to be created' }
      end
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(params[:post].permit(:title, :content))
      flash[:notice] = "Listing was successfully updated"
      redirect_to listings_path
    else
      render 'edit'
    end
  end

  def destroy
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to listings_path }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
  end

  def search
    if params[:query].length.zero?
      @users = nil
      @posts = nil
    else
      @users = User.search(params[:query])
        .records
        .paginate(page: params[:page])

      @posts = Post.search(params[:query])
        .records.where(flagged: false)
        .paginate(page: params[:page])

      @users = nil if @users.count.zero?
      @posts = nil if @posts.count.zero?
    end
      render action: 'index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.friendly.find(params[:id])
  end

#   def actors
#     @title = 'Actors'
#     @users = User.search(query: {match: {role: "actor" }}).records
#       .paginate(page: params[:page])
#
#     render action: 'index'
#   end

#   def film_makers
#     @title = 'Film Makers'
#     @users = User.search(query: {match: {role: "film maker" }}).records
#     @users.to_a
#
#     render action: 'index'
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def currently_flagged
    Post.where(flagged: true)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<!-- <div id="footer"> -->
<!--   <div class="container"> -->
<!--     <p class="text&#45;muted">© Ohio State Film and Video Society</p> -->
<!--   </div> -->
<!-- </div> -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Actors Wanted', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to current_user.name, edit_user_registration_path  %>
          </li>
          <li>
            <% if current_user.admin? && currently_flagged.count > 0 %>
              <%= link_to flagged_path, class: 'flagged_count' do %>
                Flagged (<%= currently_flagged.count %>)
              <% end %>
            <% end %>
          </li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Get Started', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_search_bar.html.erb
<div class="row search-bar">
  <div class="col-md-8 col-md-offset-2">
    <%= form_tag search_path, method: 'get', role: 'search' do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], class: 'form-control input-lg', placeholder: 'Search: actor, film maker equipment etc.' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Film and Video Society Board" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Film and Video Society Board" %>">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/retina.js/1.0.1/retina.js" %>
  <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div id="main" class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About US</h1>

app/views/pages/contact.html.erb
<h1>Contact US</h1>

app/views/posts/_basic_posts_table.html.erb
<%# <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

<table class="table table-striped table-bordered">
  <tbody>
  <% @posts.each do |post| %>
    <tr id="<%= post.id %>">
      <td><%= link_to post.title, user_post_path(post.author, post) %> by: <%= link_to post.author.name, user_path(post.author) %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/posts/destroy.js.erb
$('.delete_listing').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/posts/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

app/views/posts/flag.js.erb
$('.flag_post').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
  $('.flagged_count').text("Flagged (<%= j "#{@flagged_posts_count + 1}" %>)");
});

app/views/posts/flagged.html.erb
<h1>Currently Flagged</h1>
<br><br>

<%= render 'posts/posts_table' %>

app/views/posts/index.html.erb
<%= render 'layouts/search_bar' %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Members</h2>
    <%= render 'users/basic_users_table' %>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Listings</h2>
    <br>
    <%= render 'posts/basic_posts_table' %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 style="padding-bottom: 20px">Create a new listing</h1>
<%= form_for @post, url: user_posts_path, html: { role: "form" } do |f| %>
  <% if @post.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-6 col-md-offset-3">
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3">
    <%= f.text_area :content, class: "form-control", placeholder: "Content" %>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

app/views/posts/unflag.js.erb
$('.unflag_post').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
  $('.flagged_count').text("Flagged (<%= j "#{@flagged_posts_count - 1}" %>)");
});

app/views/search/_not_found.html.erb
<h1>Could not find any results</h1>

app/views/search/_posts.html.erb
<% if !@posts.nil? %>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

  <h3>Listings results</h3>
  <% @posts.each do |post| %>
    <p><%= post.title %></p>
    <% end %>
<% end %>

app/views/search/_users.html.erb
<% if !@users.nil? %>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>

  <h3>User results</h3>
  <% @users.each do |user| %>
    <p><%= user.name %></p>
  <% end %>
<% end %>

app/views/search/index.html.erb
<h1>Search Results</h1>

<% if @posts.nil? && @users.nil? %>
  <%= render 'search/not_found' %>
<% else %>
  <%= render 'search/users' %>
  <%= render 'search/posts' %>
<% end %>

app/views/users/_basic_users_table.html.erb
<table class="table table-striped table-bordered">
  <tbody>
    <% @users.each do |user| %>
      <tr id="<%= user.id %>">
        <td><%= link_to user.name, user_path(user) %> Joined: <%= user.created_at.to_formatted_s(:month_and_day) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h1><%= @title if !@title.nil? %></h1>

<% if @users.count > 0 %>
<% @users.each do |user| %>
  <%= user.name %>
  <% end %>
<% else %>
  <h1>Oh Dear...</h1>
  <p>
    It appears we coud not find what you were looking for,
    so sorry about that.
  </p>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>